#!/usr/bin/env python3
"""Exports the creation bytecode the ...909 vanity miner rebuilds in the
browser.

The client predicts each candidate token address with the same CREATE2 math
the deployer contract uses, which requires the exact creation code the
factory will deploy. That code lives in the compiled artifacts, so this
script must be re-run (and its output committed) whenever the contracts or
compiler settings change:

    forge build && python3 script/export-vanity-artifacts.py

Drift is not dangerous, only inert: the create page verifies every mined
salt against the deployer's own predictLaunchAddresses() before launching,
and falls back to a random salt when the prediction does not match.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "out"
DEST = ROOT.parent / "frontend" / "src" / "abis" / "initcode.ts"

def creation(name: str) -> str:
    artifact = json.loads((OUT / f"{name}.sol" / f"{name}.json").read_text())
    code = artifact["bytecode"]["object"]
    assert code.startswith("0x") and len(code) > 2, name
    version = artifact["metadata"]["compiler"]["version"]
    assert version.startswith("0.8.26"), f"{name} compiled with {version}, expected 0.8.26"
    return code

DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(
    "// Generated by contracts/script/export-vanity-artifacts.py; do not edit.\n"
    "// Creation bytecode the ...909 vanity miner rebuilds initcode from.\n"
    'export const SOLC = "0.8.26";\n'
    f'export const BONDING_CURVE_CREATION = "{creation("PopBondingCurve")}" as const;\n'
    f'export const LAUNCH_TOKEN_CREATION = "{creation("PopLaunchToken")}" as const;\n'
    f'export const REWARD_TOKEN_CREATION = "{creation("PopRewardToken")}" as const;\n'
)
print(f"wrote {DEST} ({DEST.stat().st_size} bytes)")
